name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: src/github.com/containerd/containerd.io
        fetch-depth: 25

    - uses: containerd/project-checks@v1.0.1
      with:
        working-directory: src/github.com/containerd/containerd.io
